# Generated by Django 5.2.8 on 2025-11-11 11:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок вывода (меньше = выше)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitecontent.project')),
            ],
            options={
                'verbose_name': 'Фото проекта',
                'verbose_name_plural': 'Фотографии проектов',
                'ordering': ['order', 'id'],
            },
        ),
    ]
