# Generated by Django 5.2.8 on 2025-11-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0003_projectimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='0 — обложка карточки'),
        ),
    ]
